# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandR', '0001_initial'),
        ('theWall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='LandR.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='userId',
        ),
        migrations.AlterField(
            model_name='comment',
            name='messageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='theWall.Post'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
